<?php
namespace Beekalam\IRAirports;

class AirportsArray {
    public static function IRAirportsArray() {
        return array (
  'KHA' => 
  array (
    'continent' => 'AS',
    'coordinates' => '45.1500015259, 36.733341217',
    'elevation_ft' => '4804',
    'gps_code' => 'OITH',
    'iata_code' => 'KHA',
    'ident' => 'IR-0001',
    'iso_country' => 'IR',
    'iso_region' => 'IR-02',
    'local_code' => NULL,
    'municipality' => 'Khaneh',
    'name' => 'Khaneh Airport',
    'type' => 'small_airport',
    'fa_name' => 'خانه',
  ),
  'GSM' => 
  array (
    'continent' => 'AS',
    'coordinates' => '55.902353, 26.754639',
    'elevation_ft' => '45',
    'gps_code' => 'OIKQ',
    'iata_code' => 'GSM',
    'ident' => 'IR-GSM',
    'iso_country' => 'IR',
    'iso_region' => 'IR-23',
    'local_code' => NULL,
    'municipality' => 'Qeshm',
    'name' => 'Qeshm International Airport',
    'type' => 'small_airport',
    'fa_name' => 'قشم',
  ),
  'IAQ' => 
  array (
    'continent' => 'AS',
    'coordinates' => '50.272701, 29.840099',
    'elevation_ft' => '20',
    'gps_code' => 'OI20',
    'iata_code' => 'IAQ',
    'ident' => 'OI20',
    'iso_country' => 'IR',
    'iso_region' => 'IR-06',
    'local_code' => 'OI20',
    'municipality' => NULL,
    'name' => 'Bahregan Airport',
    'type' => 'small_airport',
    'fa_name' => 'بهرگان',
  ),
  'ABD' => 
  array (
    'continent' => 'AS',
    'coordinates' => '48.2282981873, 30.371099472',
    'elevation_ft' => '10',
    'gps_code' => 'OIAA',
    'iata_code' => 'ABD',
    'ident' => 'OIAA',
    'iso_country' => 'IR',
    'iso_region' => 'IR-10',
    'local_code' => NULL,
    'municipality' => 'Abadan',
    'name' => 'Abadan Airport',
    'type' => 'medium_airport',
    'fa_name' => 'آبادان',
  ),
  'DEF' => 
  array (
    'continent' => 'AS',
    'coordinates' => '48.397598, 32.434399',
    'elevation_ft' => '474',
    'gps_code' => 'OIAD',
    'iata_code' => 'DEF',
    'ident' => 'OIAD',
    'iso_country' => 'IR',
    'iso_region' => 'IR-10',
    'local_code' => NULL,
    'municipality' => NULL,
    'name' => 'Dezful Airport',
    'type' => 'small_airport',
    'fa_name' => 'دزفول',
  ),
  'AKW' => 
  array (
    'continent' => 'AS',
    'coordinates' => '49.6772, 30.7444',
    'elevation_ft' => '88',
    'gps_code' => 'OIAG',
    'iata_code' => 'AKW',
    'ident' => 'OIAG',
    'iso_country' => 'IR',
    'iso_region' => 'IR-10',
    'local_code' => NULL,
    'municipality' => 'Aghajari',
    'name' => 'Aghajari Airport',
    'type' => 'medium_airport',
    'fa_name' => 'آقاجاری',
  ),
  'GCH' => 
  array (
    'continent' => 'AS',
    'coordinates' => '50.827999115, 30.337600708',
    'elevation_ft' => '2414',
    'gps_code' => 'OIAH',
    'iata_code' => 'GCH',
    'ident' => 'OIAH',
    'iso_country' => 'IR',
    'iso_region' => 'IR-18',
    'local_code' => NULL,
    'municipality' => 'Gachsaran',
    'name' => 'Gachsaran Airport',
    'type' => 'medium_airport',
    'fa_name' => 'گچساران',
  ),
  'OMI' => 
  array (
    'continent' => 'AS',
    'coordinates' => '49.5349006652832, 30.8351993560791',
    'elevation_ft' => '85',
    'gps_code' => 'OIAJ',
    'iata_code' => 'OMI',
    'ident' => 'OIAJ',
    'iso_country' => 'IR',
    'iso_region' => 'IR-10',
    'local_code' => NULL,
    'municipality' => 'Omidiyeh',
    'name' => 'Omidiyeh Airport',
    'type' => 'small_airport',
    'fa_name' => 'امیدیه',
  ),
  'MRX' => 
  array (
    'continent' => 'AS',
    'coordinates' => '49.15190124511719, 30.55620002746582',
    'elevation_ft' => '8',
    'gps_code' => 'OIAM',
    'iata_code' => 'MRX',
    'ident' => 'OIAM',
    'iso_country' => 'IR',
    'iso_region' => 'IR-10',
    'local_code' => NULL,
    'municipality' => NULL,
    'name' => 'Mahshahr Airport',
    'type' => 'medium_airport',
    'fa_name' => 'ماهشهر',
  ),
  'AWZ' => 
  array (
    'continent' => 'AS',
    'coordinates' => '48.7620010376, 31.337400436399996',
    'elevation_ft' => '66',
    'gps_code' => 'OIAW',
    'iata_code' => 'AWZ',
    'ident' => 'OIAW',
    'iso_country' => 'IR',
    'iso_region' => 'IR-10',
    'local_code' => NULL,
    'municipality' => 'Ahwaz',
    'name' => 'Ahwaz Airport',
    'type' => 'medium_airport',
    'fa_name' => 'اهواز',
  ),
  'AEU' => 
  array (
    'continent' => 'AS',
    'coordinates' => '55.033001, 25.8757',
    'elevation_ft' => '23',
    'gps_code' => 'OIBA',
    'iata_code' => 'AEU',
    'ident' => 'OIBA',
    'iso_country' => 'IR',
    'iso_region' => 'IR-23',
    'local_code' => NULL,
    'municipality' => 'Abu Musa',
    'name' => 'Abu Musa Island Airport',
    'type' => 'medium_airport',
    'fa_name' => 'ابوموسی',
  ),
  'BUZ' => 
  array (
    'continent' => 'AS',
    'coordinates' => '50.8345985413, 28.9447994232',
    'elevation_ft' => '68',
    'gps_code' => 'OIBB',
    'iata_code' => 'BUZ',
    'ident' => 'OIBB',
    'iso_country' => 'IR',
    'iso_region' => 'IR-06',
    'local_code' => NULL,
    'municipality' => 'Bushehr',
    'name' => 'Bushehr Airport',
    'type' => 'medium_airport',
    'fa_name' => 'بوشهر',
  ),
  'YEH' => 
  array (
    'continent' => 'AS',
    'coordinates' => '52.615501, 27.4814',
    'elevation_ft' => '15',
    'gps_code' => 'OIBI',
    'iata_code' => 'YEH',
    'ident' => 'OIBI',
    'iso_country' => 'IR',
    'iso_region' => 'IR-06',
    'local_code' => 'OI15',
    'municipality' => 'Asaloyeh',
    'name' => 'Asaloyeh Airport',
    'type' => 'closed',
    'fa_name' => 'عسلویه',
  ),
  'KNR' => 
  array (
    'continent' => 'AS',
    'coordinates' => '52.35219955444336, 27.820499420166016',
    'elevation_ft' => '2173',
    'gps_code' => 'OIBJ',
    'iata_code' => 'KNR',
    'ident' => 'OIBJ',
    'iso_country' => 'IR',
    'iso_region' => 'IR-06',
    'local_code' => NULL,
    'municipality' => 'Kangan',
    'name' => 'Jam Airport',
    'type' => 'medium_airport',
    'fa_name' => 'کنگان',
  ),
  'KIH' => 
  array (
    'continent' => 'AS',
    'coordinates' => '53.980201721200004, 26.5261993408',
    'elevation_ft' => '101',
    'gps_code' => 'OIBK',
    'iata_code' => 'KIH',
    'ident' => 'OIBK',
    'iso_country' => 'IR',
    'iso_region' => 'IR-23',
    'local_code' => NULL,
    'municipality' => 'Kish Island',
    'name' => 'Kish International Airport',
    'type' => 'medium_airport',
    'fa_name' => 'کیش',
  ),
  'BDH' => 
  array (
    'continent' => 'AS',
    'coordinates' => '54.824798584, 26.531999588',
    'elevation_ft' => '67',
    'gps_code' => 'OIBL',
    'iata_code' => 'BDH',
    'ident' => 'OIBL',
    'iso_country' => 'IR',
    'iso_region' => 'IR-23',
    'local_code' => NULL,
    'municipality' => 'Bandar Lengeh',
    'name' => 'Bandar Lengeh Airport',
    'type' => 'medium_airport',
    'fa_name' => 'بندر لنگه',
  ),
  'PGU' => 
  array (
    'continent' => 'AS',
    'coordinates' => '52.737701, 27.379601',
    'elevation_ft' => '27',
    'gps_code' => 'OIBP',
    'iata_code' => 'PGU',
    'ident' => 'OIBP',
    'iso_country' => 'IR',
    'iso_region' => 'IR-06',
    'local_code' => NULL,
    'municipality' => 'Asalouyeh',
    'name' => 'Persian Gulf International Airport',
    'type' => 'medium_airport',
    'fa_name' => 'عسلویه',
  ),
  'KHK' => 
  array (
    'continent' => 'AS',
    'coordinates' => '50.32389831542969, 29.260299682617188',
    'elevation_ft' => '17',
    'gps_code' => 'OIBQ',
    'iata_code' => 'KHK',
    'ident' => 'OIBQ',
    'iso_country' => 'IR',
    'iso_region' => 'IR-06',
    'local_code' => NULL,
    'municipality' => NULL,
    'name' => 'Khark Island Airport',
    'type' => 'medium_airport',
    'fa_name' => 'خارک',
  ),
  'SXI' => 
  array (
    'continent' => 'AS',
    'coordinates' => '54.539398193359375, 25.908899307250977',
    'elevation_ft' => '43',
    'gps_code' => 'OIBS',
    'iata_code' => 'SXI',
    'ident' => 'OIBS',
    'iso_country' => 'IR',
    'iso_region' => 'IR-23',
    'local_code' => NULL,
    'municipality' => NULL,
    'name' => 'Sirri Island Airport',
    'type' => 'medium_airport',
    'fa_name' => '',
  ),
  'LVP' => 
  array (
    'continent' => 'AS',
    'coordinates' => '53.356300354003906, 26.810300827026367',
    'elevation_ft' => '76',
    'gps_code' => 'OIBV',
    'iata_code' => 'LVP',
    'ident' => 'OIBV',
    'iso_country' => 'IR',
    'iso_region' => 'IR-23',
    'local_code' => NULL,
    'municipality' => NULL,
    'name' => 'Lavan Island Airport',
    'type' => 'medium_airport',
    'fa_name' => 'لاوان',
  ),
  'KSH' => 
  array (
    'continent' => 'AS',
    'coordinates' => '47.1581001282, 34.3459014893',
    'elevation_ft' => '4307',
    'gps_code' => 'OICC',
    'iata_code' => 'KSH',
    'ident' => 'OICC',
    'iso_country' => 'IR',
    'iso_region' => 'IR-17',
    'local_code' => NULL,
    'municipality' => 'Kermanshah',
    'name' => 'Shahid Ashrafi Esfahani Airport',
    'type' => 'medium_airport',
    'fa_name' => 'کرمانشاه',
  ),
  'IIL' => 
  array (
    'continent' => 'AS',
    'coordinates' => '46.40480041503906, 33.58660125732422',
    'elevation_ft' => '4404',
    'gps_code' => 'OICI',
    'iata_code' => 'IIL',
    'ident' => 'OICI',
    'iso_country' => 'IR',
    'iso_region' => 'IR-05',
    'local_code' => NULL,
    'municipality' => 'Ilam',
    'name' => 'Ilam Airport',
    'type' => 'medium_airport',
    'fa_name' => 'ایلام',
  ),
  'KHD' => 
  array (
    'continent' => 'AS',
    'coordinates' => '48.282901763916016, 33.43539810180664',
    'elevation_ft' => '3782',
    'gps_code' => 'OICK',
    'iata_code' => 'KHD',
    'ident' => 'OICK',
    'iso_country' => 'IR',
    'iso_region' => 'IR-20',
    'local_code' => NULL,
    'municipality' => NULL,
    'name' => 'Khoram Abad Airport',
    'type' => 'medium_airport',
    'fa_name' => 'خرم آباد',
  ),
  'SDG' => 
  array (
    'continent' => 'AS',
    'coordinates' => '47.00920104980469, 35.24589920043945',
    'elevation_ft' => '4522',
    'gps_code' => 'OICS',
    'iata_code' => 'SDG',
    'ident' => 'OICS',
    'iso_country' => 'IR',
    'iso_region' => 'IR-16',
    'local_code' => NULL,
    'municipality' => NULL,
    'name' => 'Sanandaj Airport',
    'type' => 'medium_airport',
    'fa_name' => 'سنندج',
  ),
  'IFH' => 
  array (
    'continent' => 'AS',
    'coordinates' => '51.561100006103516, 32.92890167236328',
    'elevation_ft' => '5256',
    'gps_code' => 'OIFE',
    'iata_code' => 'IFH',
    'ident' => 'OIFE',
    'iso_country' => 'IR',
    'iso_region' => 'IR-04',
    'local_code' => NULL,
    'municipality' => 'Hesa',
    'name' => 'Hesa Airport',
    'type' => 'small_airport',
    'fa_name' => '',
  ),
  'KKS' => 
  array (
    'continent' => 'AS',
    'coordinates' => '51.577, 33.895302',
    'elevation_ft' => '3465',
    'gps_code' => 'OIFK',
    'iata_code' => 'KKS',
    'ident' => 'OIFK',
    'iso_country' => 'IR',
    'iso_region' => 'IR-04',
    'local_code' => NULL,
    'municipality' => 'Kashan',
    'name' => 'Kashan Airport',
    'type' => 'medium_airport',
    'fa_name' => 'کاشان',
  ),
  'IFN' => 
  array (
    'continent' => 'AS',
    'coordinates' => '51.86130142211914, 32.75080108642578',
    'elevation_ft' => '5059',
    'gps_code' => 'OIFM',
    'iata_code' => 'IFN',
    'ident' => 'OIFM',
    'iso_country' => 'IR',
    'iso_region' => 'IR-04',
    'local_code' => NULL,
    'municipality' => 'Isfahan',
    'name' => 'Esfahan Shahid Beheshti International Airport',
    'type' => 'medium_airport',
    'fa_name' => 'اصفهان',
  ),
  'CQD' => 
  array (
    'continent' => 'AS',
    'coordinates' => '50.842201232899995, 32.2971992493',
    'elevation_ft' => '6723',
    'gps_code' => 'OIFS',
    'iata_code' => 'CQD',
    'ident' => 'OIFS',
    'iso_country' => 'IR',
    'iso_region' => 'IR-08',
    'local_code' => NULL,
    'municipality' => 'Shahrekord',
    'name' => 'Shahrekord Airport',
    'type' => 'medium_airport',
    'fa_name' => 'شهرکرد',
  ),
  'RAS' => 
  array (
    'continent' => 'AS',
    'coordinates' => '49.617778, 37.323333',
    'elevation_ft' => '-40',
    'gps_code' => 'OIGG',
    'iata_code' => 'RAS',
    'ident' => 'OIGG',
    'iso_country' => 'IR',
    'iso_region' => 'IR-19',
    'local_code' => NULL,
    'municipality' => 'Rasht',
    'name' => 'Sardar-e-Jangal Airport',
    'type' => 'medium_airport',
    'fa_name' => 'رشت',
  ),
  'HDM' => 
  array (
    'continent' => 'AS',
    'coordinates' => '48.5525016784668, 34.86920166015625',
    'elevation_ft' => '5755',
    'gps_code' => 'OIHH',
    'iata_code' => 'HDM',
    'ident' => 'OIHH',
    'iso_country' => 'IR',
    'iso_region' => 'IR-24',
    'local_code' => NULL,
    'municipality' => 'Hamadan',
    'name' => 'Hamadan Airport',
    'type' => 'medium_airport',
    'fa_name' => 'همدان',
  ),
  'AJK' => 
  array (
    'continent' => 'AS',
    'coordinates' => '49.8473014831543, 34.138099670410156',
    'elevation_ft' => '5440',
    'gps_code' => 'OIHR',
    'iata_code' => 'AJK',
    'ident' => 'OIHR',
    'iso_country' => 'IR',
    'iso_region' => 'IR-22',
    'local_code' => NULL,
    'municipality' => 'Araak',
    'name' => 'Arak Airport',
    'type' => 'small_airport',
    'fa_name' => 'اراک',
  ),
  'IKA' => 
  array (
    'continent' => 'AS',
    'coordinates' => '51.152198791503906, 35.416099548339844',
    'elevation_ft' => '3305',
    'gps_code' => 'OIIE',
    'iata_code' => 'IKA',
    'ident' => 'OIIE',
    'iso_country' => 'IR',
    'iso_region' => 'IR-07',
    'local_code' => NULL,
    'municipality' => 'Tehran',
    'name' => 'Imam Khomeini International Airport',
    'type' => 'large_airport',
    'fa_name' => 'تهران',
  ),
  'THR' => 
  array (
    'continent' => 'AS',
    'coordinates' => '51.31340026855469, 35.68920135498047',
    'elevation_ft' => '3962',
    'gps_code' => 'OIII',
    'iata_code' => 'THR',
    'ident' => 'OIII',
    'iso_country' => 'IR',
    'iso_region' => 'IR-07',
    'local_code' => NULL,
    'municipality' => 'Tehran',
    'name' => 'Mehrabad International Airport',
    'type' => 'large_airport',
    'fa_name' => 'تهران',
  ),
  'GZW' => 
  array (
    'continent' => 'AS',
    'coordinates' => '50.0471, 36.240101',
    'elevation_ft' => '4184',
    'gps_code' => 'OIIK',
    'iata_code' => 'GZW',
    'ident' => 'OIIK',
    'iso_country' => 'IR',
    'iso_region' => 'IR-28',
    'local_code' => NULL,
    'municipality' => 'Qazvin',
    'name' => 'Qazvin Airport',
    'type' => 'medium_airport',
    'fa_name' => '',
  ),
  'PYK' => 
  array (
    'continent' => 'AS',
    'coordinates' => '50.826698303223, 35.776100158691',
    'elevation_ft' => '4170',
    'gps_code' => 'OIIP',
    'iata_code' => 'PYK',
    'ident' => 'OIIP',
    'iso_country' => 'IR',
    'iso_region' => 'IR-U-A',
    'local_code' => NULL,
    'municipality' => 'Karaj',
    'name' => 'Payam International Airport',
    'type' => 'medium_airport',
    'fa_name' => 'کرج',
  ),
  'SNX' => 
  array (
    'continent' => 'AS',
    'coordinates' => '53.495098, 35.591099',
    'elevation_ft' => '3665',
    'gps_code' => 'OIIS',
    'iata_code' => 'SNX',
    'ident' => 'OIIS',
    'iso_country' => 'IR',
    'iso_region' => 'IR-12',
    'local_code' => NULL,
    'municipality' => 'Semnan',
    'name' => 'Semnan Municipal Airport',
    'type' => 'small_airport',
    'fa_name' => 'سمنان',
  ),
  'BND' => 
  array (
    'continent' => 'AS',
    'coordinates' => '56.37779998779297, 27.218299865722656',
    'elevation_ft' => '22',
    'gps_code' => 'OIKB',
    'iata_code' => 'BND',
    'ident' => 'OIKB',
    'iso_country' => 'IR',
    'iso_region' => 'IR-23',
    'local_code' => NULL,
    'municipality' => 'Bandar Abbas',
    'name' => 'Bandar Abbas International Airport',
    'type' => 'medium_airport',
    'fa_name' => 'بندرعباس',
  ),
  'JYR' => 
  array (
    'continent' => 'AS',
    'coordinates' => '57.67029953, 28.726900100699996',
    'elevation_ft' => '2663',
    'gps_code' => 'OIKJ',
    'iata_code' => 'JYR',
    'ident' => 'OIKJ',
    'iso_country' => 'IR',
    'iso_region' => 'IR-15',
    'local_code' => NULL,
    'municipality' => 'Jiroft',
    'name' => 'Jiroft Airport',
    'type' => 'medium_airport',
    'fa_name' => 'جیرفت',
  ),
  'KER' => 
  array (
    'continent' => 'AS',
    'coordinates' => '56.9510993958, 30.274400711099997',
    'elevation_ft' => '5741',
    'gps_code' => 'OIKK',
    'iata_code' => 'KER',
    'ident' => 'OIKK',
    'iso_country' => 'IR',
    'iso_region' => 'IR-15',
    'local_code' => NULL,
    'municipality' => 'Kerman',
    'name' => 'Kerman Airport',
    'type' => 'medium_airport',
    'fa_name' => 'کرمان',
  ),
  'BXR' => 
  array (
    'continent' => 'AS',
    'coordinates' => '58.45000076293945, 29.084199905395508',
    'elevation_ft' => '3231',
    'gps_code' => 'OIKM',
    'iata_code' => 'BXR',
    'ident' => 'OIKM',
    'iso_country' => 'IR',
    'iso_region' => 'IR-15',
    'local_code' => NULL,
    'municipality' => NULL,
    'name' => 'Bam Airport',
    'type' => 'medium_airport',
    'fa_name' => 'بام',
  ),
  'HDR' => 
  array (
    'continent' => 'AS',
    'coordinates' => '56.17250061035156, 27.158300399780273',
    'elevation_ft' => '19',
    'gps_code' => 'OIKP',
    'iata_code' => 'HDR',
    'ident' => 'OIKP',
    'iso_country' => 'IR',
    'iso_region' => 'IR-23',
    'local_code' => NULL,
    'municipality' => 'Havadarya',
    'name' => 'Havadarya Airport',
    'type' => 'small_airport',
    'fa_name' => 'هوادریا',
  ),
  'RJN' => 
  array (
    'continent' => 'AS',
    'coordinates' => '56.05110168457031, 30.297700881958008',
    'elevation_ft' => '5298',
    'gps_code' => 'OIKR',
    'iata_code' => 'RJN',
    'ident' => 'OIKR',
    'iso_country' => 'IR',
    'iso_region' => 'IR-15',
    'local_code' => NULL,
    'municipality' => NULL,
    'name' => 'Rafsanjan Airport',
    'type' => 'medium_airport',
    'fa_name' => 'رفسنجان',
  ),
  'SYJ' => 
  array (
    'continent' => 'AS',
    'coordinates' => '55.672698974609375, 29.550899505615234',
    'elevation_ft' => '5846',
    'gps_code' => 'OIKY',
    'iata_code' => 'SYJ',
    'ident' => 'OIKY',
    'iso_country' => 'IR',
    'iso_region' => 'IR-15',
    'local_code' => NULL,
    'municipality' => NULL,
    'name' => 'Sirjan Airport',
    'type' => 'medium_airport',
    'fa_name' => 'سیرجان',
  ),
  'XBJ' => 
  array (
    'continent' => 'AS',
    'coordinates' => '59.2661018371582, 32.898101806640625',
    'elevation_ft' => '4952',
    'gps_code' => 'OIMB',
    'iata_code' => 'XBJ',
    'ident' => 'OIMB',
    'iso_country' => 'IR',
    'iso_region' => 'IR-29',
    'local_code' => NULL,
    'municipality' => 'Birjand',
    'name' => 'Birjand Airport',
    'type' => 'medium_airport',
    'fa_name' => 'بیرجند',
  ),
  'CKT' => 
  array (
    'continent' => 'AS',
    'coordinates' => '61.06489944458008, 36.50120162963867',
    'elevation_ft' => '945',
    'gps_code' => 'OIMC',
    'iata_code' => 'CKT',
    'ident' => 'OIMC',
    'iso_country' => 'IR',
    'iso_region' => 'IR-30',
    'local_code' => NULL,
    'municipality' => 'Sarakhs',
    'name' => 'Sarakhs Airport',
    'type' => 'medium_airport',
    'fa_name' => 'سرخس',
  ),
  'RUD' => 
  array (
    'continent' => 'AS',
    'coordinates' => '55.104198455799995, 36.4253005981',
    'elevation_ft' => '4215',
    'gps_code' => 'OIMJ',
    'iata_code' => 'RUD',
    'ident' => 'OIMJ',
    'iso_country' => 'IR',
    'iso_region' => 'IR-12',
    'local_code' => NULL,
    'municipality' => NULL,
    'name' => 'Shahroud Airport',
    'type' => 'small_airport',
    'fa_name' => 'شاهرود',
  ),
  'MHD' => 
  array (
    'continent' => 'AS',
    'coordinates' => '59.64099884033203, 36.235198974609375',
    'elevation_ft' => '3263',
    'gps_code' => 'OIMM',
    'iata_code' => 'MHD',
    'ident' => 'OIMM',
    'iso_country' => 'IR',
    'iso_region' => 'IR-30',
    'local_code' => NULL,
    'municipality' => 'Mashhad',
    'name' => 'Mashhad International Airport',
    'type' => 'large_airport',
    'fa_name' => 'مشهد',
  ),
  'BJB' => 
  array (
    'continent' => 'AS',
    'coordinates' => '57.30820083618164, 37.49300003051758',
    'elevation_ft' => '3499',
    'gps_code' => 'OIMN',
    'iata_code' => 'BJB',
    'ident' => 'OIMN',
    'iso_country' => 'IR',
    'iso_region' => 'IR-31',
    'local_code' => NULL,
    'municipality' => 'Bojnord',
    'name' => 'Bojnord Airport',
    'type' => 'medium_airport',
    'fa_name' => 'بجنورد',
  ),
  'AFZ' => 
  array (
    'continent' => 'AS',
    'coordinates' => '57.59519958496094, 36.16809844970703',
    'elevation_ft' => '3010',
    'gps_code' => 'OIMS',
    'iata_code' => 'AFZ',
    'ident' => 'OIMS',
    'iso_country' => 'IR',
    'iso_region' => 'IR-30',
    'local_code' => NULL,
    'municipality' => 'Sabzevar',
    'name' => 'Sabzevar National Airport',
    'type' => 'medium_airport',
    'fa_name' => 'سبزوار',
  ),
  'TCX' => 
  array (
    'continent' => 'AS',
    'coordinates' => '56.8927001953, 33.6678009033',
    'elevation_ft' => '2312',
    'gps_code' => 'OIMT',
    'iata_code' => 'TCX',
    'ident' => 'OIMT',
    'iso_country' => 'IR',
    'iso_region' => 'IR-25',
    'local_code' => NULL,
    'municipality' => 'Tabas',
    'name' => 'Tabas Airport',
    'type' => 'medium_airport',
    'fa_name' => 'طبس',
  ),
  'KLM' => 
  array (
    'continent' => 'AS',
    'coordinates' => '55.4519996643, 37.3833007812',
    'elevation_ft' => '425',
    'gps_code' => 'OINE',
    'iata_code' => 'KLM',
    'ident' => 'OINE',
    'iso_country' => 'IR',
    'iso_region' => 'IR-27',
    'local_code' => NULL,
    'municipality' => 'Kalaleh',
    'name' => 'Kalaleh Airport',
    'type' => 'small_airport',
    'fa_name' => 'کلاله',
  ),
  'GBT' => 
  array (
    'continent' => 'AS',
    'coordinates' => '54.4012985229, 36.909400939899996',
    'elevation_ft' => '-24',
    'gps_code' => 'OING',
    'iata_code' => 'GBT',
    'ident' => 'OING',
    'iso_country' => 'IR',
    'iso_region' => 'IR-27',
    'local_code' => NULL,
    'municipality' => 'Gorgan',
    'name' => 'Gorgan Airport',
    'type' => 'medium_airport',
    'fa_name' => 'گرگان',
  ),
  'BSM' => 
  array (
    'continent' => 'AS',
    'coordinates' => '52.34960174560547, 36.65510177612305',
    'elevation_ft' => '-79',
    'gps_code' => 'OINJ',
    'iata_code' => 'BSM',
    'ident' => 'OINJ',
    'iso_country' => 'IR',
    'iso_region' => 'IR-21',
    'local_code' => NULL,
    'municipality' => 'Amol',
    'name' => 'Bishe Kola Air Base',
    'type' => 'small_airport',
    'fa_name' => 'آمل',
  ),
  'NSH' => 
  array (
    'continent' => 'AS',
    'coordinates' => '51.464698791503906, 36.663299560546875',
    'elevation_ft' => '-61',
    'gps_code' => 'OINN',
    'iata_code' => 'NSH',
    'ident' => 'OINN',
    'iso_country' => 'IR',
    'iso_region' => 'IR-21',
    'local_code' => NULL,
    'municipality' => NULL,
    'name' => 'Noshahr Airport',
    'type' => 'medium_airport',
    'fa_name' => 'نوشهر',
  ),
  'RZR' => 
  array (
    'continent' => 'AS',
    'coordinates' => '50.67959976196289, 36.9099006652832',
    'elevation_ft' => '-70',
    'gps_code' => 'OINR',
    'iata_code' => 'RZR',
    'ident' => 'OINR',
    'iso_country' => 'IR',
    'iso_region' => 'IR-21',
    'local_code' => NULL,
    'municipality' => NULL,
    'name' => 'Ramsar Airport',
    'type' => 'medium_airport',
    'fa_name' => 'رامسر',
  ),
  'SRY' => 
  array (
    'continent' => 'AS',
    'coordinates' => '53.193599700899995, 36.635799408',
    'elevation_ft' => '35',
    'gps_code' => 'OINZ',
    'iata_code' => 'SRY',
    'ident' => 'OINZ',
    'iso_country' => 'IR',
    'iso_region' => 'IR-21',
    'local_code' => NULL,
    'municipality' => 'Sari',
    'name' => 'Dasht-e Naz Airport',
    'type' => 'medium_airport',
    'fa_name' => 'ساری',
  ),
  'FAZ' => 
  array (
    'continent' => 'AS',
    'coordinates' => '53.72330093383789, 28.891799926757812',
    'elevation_ft' => '4261',
    'gps_code' => 'OISF',
    'iata_code' => 'FAZ',
    'ident' => 'OISF',
    'iso_country' => 'IR',
    'iso_region' => 'IR-14',
    'local_code' => NULL,
    'municipality' => 'Fasa',
    'name' => 'Fasa Airport',
    'type' => 'medium_airport',
    'fa_name' => 'فسا',
  ),
  'JAR' => 
  array (
    'continent' => 'AS',
    'coordinates' => '53.5791015625, 28.586700439499996',
    'elevation_ft' => '3358',
    'gps_code' => 'OISJ',
    'iata_code' => 'JAR',
    'ident' => 'OISJ',
    'iso_country' => 'IR',
    'iso_region' => 'IR-14',
    'local_code' => NULL,
    'municipality' => 'Jahrom',
    'name' => 'Jahrom Airport',
    'type' => 'small_airport',
    'fa_name' => 'جهرم',
  ),
  'LRR' => 
  array (
    'continent' => 'AS',
    'coordinates' => '54.3833007812, 27.6746997833',
    'elevation_ft' => '2641',
    'gps_code' => 'OISL',
    'iata_code' => 'LRR',
    'ident' => 'OISL',
    'iso_country' => 'IR',
    'iso_region' => 'IR-14',
    'local_code' => NULL,
    'municipality' => 'Lar',
    'name' => 'Lar Airport',
    'type' => 'medium_airport',
    'fa_name' => 'لار',
  ),
  'LFM' => 
  array (
    'continent' => 'AS',
    'coordinates' => '53.18880081179999, 27.3726997375',
    'elevation_ft' => '1337',
    'gps_code' => 'OISR',
    'iata_code' => 'LFM',
    'ident' => 'OISR',
    'iso_country' => 'IR',
    'iso_region' => 'IR-14',
    'local_code' => NULL,
    'municipality' => 'Lamerd',
    'name' => 'Lamerd Airport',
    'type' => 'small_airport',
    'fa_name' => 'لامرد',
  ),
  'SYZ' => 
  array (
    'continent' => 'AS',
    'coordinates' => '52.589802, 29.5392',
    'elevation_ft' => '4927',
    'gps_code' => 'OISS',
    'iata_code' => 'SYZ',
    'ident' => 'OISS',
    'iso_country' => 'IR',
    'iso_region' => 'IR-14',
    'local_code' => NULL,
    'municipality' => 'Shiraz',
    'name' => 'Shiraz Shahid Dastghaib International Airport',
    'type' => 'large_airport',
    'fa_name' => 'شیراز',
  ),
  'YES' => 
  array (
    'continent' => 'AS',
    'coordinates' => '51.545101165771, 30.700500488281',
    'elevation_ft' => '5939',
    'gps_code' => 'OISY',
    'iata_code' => 'YES',
    'ident' => 'OISY',
    'iso_country' => 'IR',
    'iso_region' => 'IR-18',
    'local_code' => NULL,
    'municipality' => 'Yasouj',
    'name' => 'Yasouj Airport',
    'type' => 'medium_airport',
    'fa_name' => 'یاسوج',
  ),
  'KHY' => 
  array (
    'continent' => 'AS',
    'coordinates' => '44.97359848022461, 38.4275016784668',
    'elevation_ft' => '3981',
    'gps_code' => 'OITK',
    'iata_code' => 'KHY',
    'ident' => 'OITK',
    'iso_country' => 'IR',
    'iso_region' => 'IR-02',
    'local_code' => NULL,
    'municipality' => 'Khoy',
    'name' => 'Khoy Airport',
    'type' => 'small_airport',
    'fa_name' => 'خوی',
  ),
  'ADU' => 
  array (
    'continent' => 'AS',
    'coordinates' => '48.4244003296, 38.3256988525',
    'elevation_ft' => '4315',
    'gps_code' => 'OITL',
    'iata_code' => 'ADU',
    'ident' => 'OITL',
    'iso_country' => 'IR',
    'iso_region' => 'IR-03',
    'local_code' => NULL,
    'municipality' => 'Ardabil',
    'name' => 'Ardabil Airport',
    'type' => 'medium_airport',
    'fa_name' => 'اردبیل',
  ),
  'ACP' => 
  array (
    'continent' => 'AS',
    'coordinates' => '46.127899169921875, 37.347999572753906',
    'elevation_ft' => '4396',
    'gps_code' => 'OITM',
    'iata_code' => 'ACP',
    'ident' => 'OITM',
    'iso_country' => 'IR',
    'iso_region' => 'IR-01',
    'local_code' => NULL,
    'municipality' => 'Maragheh',
    'name' => 'Sahand Airport',
    'type' => 'small_airport',
    'fa_name' => 'مراغه',
  ),
  'PFQ' => 
  array (
    'continent' => 'AS',
    'coordinates' => '47.881500244141, 39.60359954834',
    'elevation_ft' => '251',
    'gps_code' => 'OITP',
    'iata_code' => 'PFQ',
    'ident' => 'OITP',
    'iso_country' => 'IR',
    'iso_region' => 'IR-03',
    'local_code' => NULL,
    'municipality' => 'Parsabad',
    'name' => 'Parsabade Moghan Airport',
    'type' => 'small_airport',
    'fa_name' => 'پارس آباد',
  ),
  'OMH' => 
  array (
    'continent' => 'AS',
    'coordinates' => '45.0686988831, 37.6680984497',
    'elevation_ft' => '4343',
    'gps_code' => 'OITR',
    'iata_code' => 'OMH',
    'ident' => 'OITR',
    'iso_country' => 'IR',
    'iso_region' => 'IR-02',
    'local_code' => NULL,
    'municipality' => 'Urmia',
    'name' => 'Urmia Airport',
    'type' => 'medium_airport',
    'fa_name' => 'ارومیه',
  ),
  'TBZ' => 
  array (
    'continent' => 'AS',
    'coordinates' => '46.23500061035156, 38.1338996887207',
    'elevation_ft' => '4459',
    'gps_code' => 'OITT',
    'iata_code' => 'TBZ',
    'ident' => 'OITT',
    'iso_country' => 'IR',
    'iso_region' => 'IR-01',
    'local_code' => NULL,
    'municipality' => 'Tabriz',
    'name' => 'Tabriz International Airport',
    'type' => 'large_airport',
    'fa_name' => 'تبریز',
  ),
  'IMQ' => 
  array (
    'continent' => 'AS',
    'coordinates' => '44.43, 39.330002',
    'elevation_ft' => NULL,
    'gps_code' => 'OITU',
    'iata_code' => 'IMQ',
    'ident' => 'OITU',
    'iso_country' => 'IR',
    'iso_region' => 'IR-02',
    'local_code' => NULL,
    'municipality' => 'Showt',
    'name' => 'Maku National Airport',
    'type' => 'small_airport',
    'fa_name' => 'ماکو',
  ),
  'JWN' => 
  array (
    'continent' => 'AS',
    'coordinates' => '48.3594017029, 36.7737007141',
    'elevation_ft' => '5382',
    'gps_code' => 'OITZ',
    'iata_code' => 'JWN',
    'ident' => 'OITZ',
    'iso_country' => 'IR',
    'iso_region' => 'IR-11',
    'local_code' => NULL,
    'municipality' => 'Zanjan',
    'name' => 'Zanjan Airport',
    'type' => 'medium_airport',
    'fa_name' => 'زنجان',
  ),
  'AZD' => 
  array (
    'continent' => 'AS',
    'coordinates' => '54.2765007019, 31.9048995972',
    'elevation_ft' => '4054',
    'gps_code' => 'OIYY',
    'iata_code' => 'AZD',
    'ident' => 'OIYY',
    'iso_country' => 'IR',
    'iso_region' => 'IR-25',
    'local_code' => NULL,
    'municipality' => 'Yazd',
    'name' => 'Shahid Sadooghi Airport',
    'type' => 'medium_airport',
    'fa_name' => 'یزد',
  ),
  'ACZ' => 
  array (
    'continent' => 'AS',
    'coordinates' => '61.54389953613281, 31.09830093383789',
    'elevation_ft' => '1628',
    'gps_code' => 'OIZB',
    'iata_code' => 'ACZ',
    'ident' => 'OIZB',
    'iso_country' => 'IR',
    'iso_region' => 'IR-13',
    'local_code' => NULL,
    'municipality' => NULL,
    'name' => 'Zabol Airport',
    'type' => 'medium_airport',
    'fa_name' => 'زابل',
  ),
  'ZBR' => 
  array (
    'continent' => 'AS',
    'coordinates' => '60.3820991516, 25.443300247199996',
    'elevation_ft' => '43',
    'gps_code' => 'OIZC',
    'iata_code' => 'ZBR',
    'ident' => 'OIZC',
    'iso_country' => 'IR',
    'iso_region' => 'IR-13',
    'local_code' => NULL,
    'municipality' => 'Chabahar',
    'name' => 'Konarak Airport',
    'type' => 'medium_airport',
    'fa_name' => 'چابهار',
  ),
  'ZAH' => 
  array (
    'continent' => 'AS',
    'coordinates' => '60.90620040893555, 29.47570037841797',
    'elevation_ft' => '4564',
    'gps_code' => 'OIZH',
    'iata_code' => 'ZAH',
    'ident' => 'OIZH',
    'iso_country' => 'IR',
    'iso_region' => 'IR-13',
    'local_code' => NULL,
    'municipality' => 'Zahedan',
    'name' => 'Zahedan International Airport',
    'type' => 'medium_airport',
    'fa_name' => 'زاهدان',
  ),
  'IHR' => 
  array (
    'continent' => 'AS',
    'coordinates' => '60.7200012207, 27.2360992432',
    'elevation_ft' => '2040',
    'gps_code' => 'OIZI',
    'iata_code' => 'IHR',
    'ident' => 'OIZI',
    'iso_country' => 'IR',
    'iso_region' => 'IR-13',
    'local_code' => NULL,
    'municipality' => 'Iranshahr',
    'name' => 'Iran Shahr Airport',
    'type' => 'medium_airport',
    'fa_name' => 'ایرانشهر',
  ),
  'JSK' => 
  array (
    'continent' => 'AS',
    'coordinates' => '57.799301, 25.653601',
    'elevation_ft' => '19',
    'gps_code' => 'OIZJ',
    'iata_code' => 'JSK',
    'ident' => 'OIZJ',
    'iso_country' => 'IR',
    'iso_region' => 'IR-23',
    'local_code' => NULL,
    'municipality' => 'Jask',
    'name' => 'Jask Airport',
    'type' => 'small_airport',
    'fa_name' => 'جاسک',
  ),
);
    }
}